task.wait(5)
getgenv().ConfigsKaitun = {
	Beta_Fix_Data_Sync = true,

	NoDeletePlayer = false,

	["Block Pet Gift"] = true,

	Collect_Cooldown = 300,
	JustFuckingCollectAll = false, -- Collect all (fruit not wait mutation) -- cooldown to collect fruit

	["Low Cpu"] = true,
	["Auto Rejoin"] = false,
	
	["Rejoin When Update"] = false,
	["Limit Tree"] = {
		["Limit"] = 200,
		["Destroy Untill"] = 150,
		
		["Safe Tree"] = {
			"Moon Blossom",
			"Bone Blossom",
			"Moon Melon",
			"Maple Apple",
			"Moon Mango",
			"Dragon Pepper",
			"Elephant Ears",
			"Fossilight",
			"Princess Thorn",
            ["Blueberry"] = 12,
            ["Strawberry"] = 12,
            ["Apple"] = 10,
            ["Coconut"] = 12,
            ["Dragon Fruit"] = 12,
            ["Mango"] = 12,
            ["Tomato"] = 20,
            ["Cactus"] = 12,
		}
	},

	Seed = {
		Buy = {
			Mode = "Custom", -- Custom , Auto
			Custom = {
				"Carrot",
                "Blueberry",
                "Grape",
                "Strawberry",
                "Elder Strawberry",
                "Wild Carrot",
                "Taro Flower",
                "Mandrake",
                "Rhubarb",
                "Onion",
                "Tall Asparagus",
                "Candy Sunflowers",
                "Red Lollipop",
                "Sugarglaze",
                "Cherry Blossom",
                "Crocus",
                "Daffodil",
                "Orange Tulip",
                "Nightshade",
                "Moonflower",
                "Moon Blossom",
                "Rose",
                "Foxglove",
                "Lilac",
                "Pink Lily",
                "Purple Dagila",
                "Sunflower",
                "Lavender",
                "Honeysuckle",
                "Manuka Flower",
                "Ember Lily",
                "Parasol Flower",
                "Rosy Delight",
                "Lily Of The Valley",
                "Burning Bud",
                "Rafflesia",
                "Stonebite",
                "Liberty Lily",
                "Firework Flower",
                "Serenity",
                "Moboblooma",
                "Soft Sunshine",
                "Hinomai",
                "Zenflare",
                "Dezen",
                "Artichoke",
                "Veinpetal",
                "Flare Daisy",
                "Tranquil Bloom",
                "Apple",
                "Avocado",
                "Banana",
                "Coconut",
                "Dragon Fruit",
                "Durian",
                "Mango",
                "Pear",
                "Pineapple",
                "Watermelon",
                "Starfruit",
                "Blood Banana",
                "Moon Melon",
                "Moon Mango",
                "Nectarine",
                "Hive Fruit",
                "Green Apple",
                "Sugar Apple",
                "Traveler's Fruit",
                "Loquat",
                "Kiwi",
                "Maple Apple",
                "Spiked Mango",
                "Crown Melon",
                "Grand Tomato",
                "Pricklefruit",
                "Mangosteen",
                "Canary Melon",
                "Pumpkin",
                "Tomato",
                "Cantaloupe",
                "Cacao",
                "Beanstalk",
                "Mint",
                "Moonglow",
                "Elephant Ears",
                "Cauliflower",
                "Pitcher Plant",
                "Firefly Fern",
                "Giant Pinecone",
                "Soft Sunshine",
                "Dragon Sapling",
                "Sakura Bush",
                "Princess Thorn",
                "Romanesco",
                "Nectar Thorn",
                "Papaya",
                "Cocovine",
                "Pepper",
                "Dragon Pepper",
                "Bell Pepper",
                "Jalapeno",
                "Badlands Pepper",
                "Feijoa",
                "Duskpuff",
                "Gleamroot",
                "Amberheart",
                "Cactus",
                "Horned Dinoshroom",
                "Twisted Tangle",
                "Sinisterdrip",
                "Amber Spine",
                "Mushroom",
                "Grand Volcania",
                "Bamboo",
                "Bendboo",
                "Lotus",
                "Lucky Bamboo",
                "Spring Onion",
                "Poseidon Plant",
                "Delphinium",
                "Guanabanana",
                "Butternut Squash",
                "Paradise Petal",
                "Boneboo",
                "Fossilight",
                "Bone Blossom",
                "Gorsetail",
                "Lingonberry",
                "Zen Rocks",
                "Enkaku",
                "Corn",

			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot"
			},
			Lock = {

			}
		}
	},
	
	["Seed Pack"] = {
		Locked = {
			
		}
	},
	
	Events = {
		["Bean Event"] = {
			Minimum_Money = 100_000, -- minimum money to start play this event
		},
		MaxMoney_Restocks = 5_000_000_000,
		Shop = { -- delete -- to buy
			"Sprout Egg",
			"Sprout Seed Pack",
			"Mandrake",
			"Silver Fertilizer",
			-- "Canary Melon",
			-- "Amberheart",
			"Spriggan",
		},
		["Traveling Shop"] = {
            "Bee Egg",
			"Bald Eagle",
            "Cauliflower",
            "Rafflesia",
            "Green Apple",
            "Avocado",
            "Banana",
            "Pineapple",
            "Kiwi",
            "Bell Pepper",
            "Prickly Pear",
            "Loquat",
            "Feijoa",
            "Pitcher Plant",
            "Flower Seed Pack"
		},
		Craft = {
			"Primal Egg",
			"Ancient Seed Pack",
			"Anti Bee Egg",
			--"Honeysuckle",
			--"Lightning Rod",
		},
		Start_Do_Honey = 100_000
	},
	
	Gear = {
		Buy = { 
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Medium Toy",
			"Medium Treat",
			"Level Up Lollipop",
			"Tanning Mirror",
			"Grandmaster Spinkler"
		},
		Lock = {

		},
	},

	Eggs = {
		Place = {
			"Sprout Egg",
			"Gourmet Egg",
			"Zen Egg",
			"Anti Bee Egg",
			"Primal Egg",
			"Bug Egg",
			"Paradise Egg",
			"Night Egg",
			"Dinosaur Egg",
			"Oasis Egg",
			--"Mythical Egg",
			--"Legendary Egg",
			"Common Summer Egg",
			"Rare Egg",
			"Uncommon Egg",
		},
		Buy = {
			"Sprout Egg",
			"Gourmet Egg",
			"Zen Egg",
			"Primal Egg",
			"Night Egg",
			"Bug Egg",
			"Anti Bee Egg",
			"Dinosaur Egg",
			"Oasis Egg",
			"Paradise Egg",
			--"Mythical Egg",
			"Legendary Egg",
			"Bee Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg",
			"Uncommon Egg",
			"Common Egg"
		}
	},
	
	Pets = {
		["Start Delete Pet At"] = 40,
		["Upgrade Slot"] = {
			["Pet"] = {
				--["Bacon Pig"] = { 8, 75, 1 },
				["Starfish"] = { 8, 75, 1 },
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				["Tarantula Hawk"] = { 2, 101, 1 },
				--["Gorilla Chef"] = { 8, 101, 1 },
				--["Bacon Pig"] = { 8, 101, 2 },
				--["Tanchozuru"] = { 8, 101, 3 },
				--["Kappa"] = { 8, 101, 4 },
				--["Spaghetti Sloth"] = { 8, 101, 5 },
				--["Corrupted Kodama"] = { 8, 101, 6 },
				--["Kodama"] = { 8, 101, 7 },
				["Blood Kiwi"] = { 8, 101, 2 },
				["Rooster"] = { 8, 101, 3 },
				["Sunny-Side Chicken"] = { 1, 101, 4 },
				["Starfish"] = { 8, 75, 5 },
			},
		},
		Favorite_LockedPet = true,
		Locked = {
			"Disco Bee",
			"Butterfly",
			"Mimic Octopus",
			"Queen Bee",
			"Dragonfly",
			"Raccoon",
			"Red Fox",
			"Fennec Fox",
			"Bald Eagle",
			"T-Rex",
			"Brontosaurus",
			"Spinosaurus",
			"Kitsune",
			"Dilophosaurus",
			"Corrupted Kitsune",
			"Raiju",
			"French Fry Ferret",
			"Lobster Thermidor",
			"Golden Goose",
			["Spriggan"] = 5,
			["Sunny-Side Chicken"] = 1,
			["Ostrich"] = 5,
			["Corrupted Kodama"] = 8,
			["Tarantula Hawk"] = 2,
			["Bald Eagle"] = 5,
			["Moon Cat"] = 10,
			["Chicken"] = 2,
			["Rooster"] = 2,
			["Blood Kiwi"] = 5,
			["Starfish"] = 8,
		},
		LockPet_Weight = 5, -- if Weight >= 7 they will locked,
		Instant_Sell = {
			"Grey Mouse",
			"Squirrel",
			"Snail",
			"Orangutan",
			"Brown Mouse",
			"Bunny",
			"Crab",
			"Caterpillar",
			"Shiba Inu",
			"Tanuki",
			"Manaki-Neko",
			"Seagull",
		}
	},

	Webhook = {
		UrlPet = "https://discord.com/api/webhooks/1399732832762331177/PVr6gW2RG2Gokz2CQEtZuJ_BplaBiIZmd8hzTj1Q8FkdoBdCjGo62NuKW0_6puoYpZLS",
		UrlSeed = "",
		PcName = "remia1234",
		
		Noti = {
			Seeds = {
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Honeysuckle",
				"Bone Blossom",
				"Fossilight",
				"Maple Apple",
				"Grand Tomato",
			},
			SeedPack = {
				"Idk"
			},
			Pets = {
				"Disco Bee",
				"Butterfly",
				"Mimic Octopus",
				"Queen Bee",
				"Dragonfly",
				"Raccoon",
				"Red Fox",
				"Fennec Fox",
				"Bald Eagle",
				"T-Rex",
				"Brontosaurus",
				"Spinosaurus",
				"Dilophosaurus",
				"Ankylosaurus",
				"Kitsune",
				"Corrupted Kitsune",
				"Raiju",
				"French Fry Ferret",
				"Lobster Thermidor",
				"Golden Goose",
			},
			Pet_Weight_Noti = true,
		}
	},
}
License = "O0ckL79tK6KwnmX2uanEfo7bosg2uYQt"
loadstring(game:HttpGet('https://raw.githubusercontent.com/Real-Aya/Loader/main/Init.lua'))()
--https://discord.com/api/webhooks/1399732832762331177/PVr6gW2RG2Gokz2CQEtZuJ_BplaBiIZmd8hzTj1Q8FkdoBdCjGo62NuKW0_6puoYpZLS
