setfpscap(5)
task.wait(5)
getgenv().ConfigsKaitun = {
	Beta_Fix_Data_Sync = true,

	NoDeletePlayer = false,

	["Block Pet Gift"] = true,

	Collect_Cooldown = 150,

	["Low Cpu"] = true,
	["Auto Rejoin"] = false,
	
	["Rejoin When Update"] = false,
	["Limit Tree"] = {
		["Limit"] = 250,
		["Destroy Untill"] = 250,
		
		["Safe Tree"] = {
			"Moon Blossom",
			"Bone Blossom",
			"Moon Melon",
			"Maple Apple",
			"Moon Mango",
			"Dragon Pepper",
			"Elephant Ears",
			"Fossilight",
			"Princess Thorn",
			-- for the event
			Bamboo = 4,
			Coconut = 4,
			Mushroom = 4,
			Glowthorn = 4,
			Tomato = 4,
			Pumpkin = 4,
			Pepper = 4,
			Cacao = 4,
			Apple = 4,
			Romanesco = 4,
			["Elder Strawberry"] = 4,
			["Burning Bud"] = 4,
			["Giant Pinecone"] = 4,
			Corn = 4,
			["Sugar Apple"] = 4,
			["Ember Lily"] = 4,
			["Dragon Fruit"] = 4,
			Sunbulb = 4,
			["Orange Tulip"] = 4,
			Blueberry = 4,
			Watermelon = 4,
			Mango = 4,
			Cactus = 4,
			Strawberry = 4,
			Beanstalk = 4,
			Lightshoot = 4,
			Grape = 4,
			Daffodil = 4,
		}
	},

	Seed = {
		Buy = {
			Mode = "Custom", -- Custom , Auto
			Custom = {
				"Carrot",
                "Blueberry",
                "Grape",
                "Strawberry",
                "Elder Strawberry",
                "Wild Carrot",
                "Taro Flower",
                "Mandrake",
                "Rhubarb",
                "Onion",
                "Tall Asparagus",
                "Candy Sunflowers",
                "Red Lollipop",
                "Sugarglaze",
                "Cherry Blossom",
                "Crocus",
                "Daffodil",
                "Orange Tulip",
                "Nightshade",
                "Moonflower",
                "Moon Blossom",
                "Rose",
                "Foxglove",
                "Lilac",
                "Pink Lily",
                "Purple Dagila",
                "Sunflower",
                "Lavender",
                "Honeysuckle",
                "Manuka Flower",
                "Ember Lily",
                "Parasol Flower",
                "Rosy Delight",
                "Lily Of The Valley",
                "Burning Bud",
                "Rafflesia",
                "Stonebite",
                "Liberty Lily",
                "Firework Flower",
                "Serenity",
                "Moboblooma",
                "Soft Sunshine",
                "Hinomai",
                "Zenflare",
                "Dezen",
                "Artichoke",
                "Veinpetal",
                "Flare Daisy",
                "Tranquil Bloom",
                "Apple",
                "Avocado",
                "Banana",
                "Coconut",
                "Dragon Fruit",
                "Durian",
                "Mango",
                "Pear",
                "Pineapple",
                "Watermelon",
                "Starfruit",
                "Blood Banana",
                "Moon Melon",
                "Moon Mango",
                "Nectarine",
                "Hive Fruit",
                "Green Apple",
                "Sugar Apple",
                "Traveler's Fruit",
                "Loquat",
                "Kiwi",
                "Maple Apple",
                "Spiked Mango",
                "Crown Melon",
                "Grand Tomato",
                "Pricklefruit",
                "Mangosteen",
                "Canary Melon",
                "Pumpkin",
                "Tomato",
                "Cantaloupe",
                "Cacao",
                "Beanstalk",
                "Mint",
                "Moonglow",
                "Elephant Ears",
                "Cauliflower",
                "Pitcher Plant",
                "Firefly Fern",
                "Giant Pinecone",
                "Soft Sunshine",
                "Dragon Sapling",
                "Sakura Bush",
                "Princess Thorn",
                "Romanesco",
                "Nectar Thorn",
                "Papaya",
                "Cocovine",
                "Pepper",
                "Dragon Pepper",
                "Bell Pepper",
                "Jalapeno",
                "Badlands Pepper",
                "Feijoa",
                "Duskpuff",
                "Gleamroot",
                "Amberheart",
                "Cactus",
                "Horned Dinoshroom",
                "Twisted Tangle",
                "Sinisterdrip",
                "Amber Spine",
                "Mushroom",
                "Grand Volcania",
                "Bamboo",
                "Bendboo",
                "Lotus",
                "Lucky Bamboo",
                "Spring Onion",
                "Poseidon Plant",
                "Delphinium",
                "Guanabanana",
                "Butternut Squash",
                "Paradise Petal",
                "Boneboo",
                "Fossilight",
                "Bone Blossom",
                "Gorsetail",
                "Lingonberry",
                "Zen Rocks",
                "Enkaku",
                "Corn",
				"Crown of Thorns",
				"Calla Lily",
				"Cyclamen",
				"Sunbulb",
				"Glowthorn",
				"Lightshoot",
				"Briar Rose",
				"Spirit Flower",
				"Wispwing",

			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot"
			},
			Lock = {

			}
		}
	},
	
	["Seed Pack"] = {
		Locked = {
			
		}
	},
	
	Events = {
		["Fairy Event"] = {
			Minimum_Money = 100000, -- minimum money to start play this event
			Rewards_Item = { -- top mean select first
				"Pet Shard Glimmering",
				"Enchanted Egg",
				"Mutation Spray Glimmering",
				"FairyPoints",
				"Fairy Targeter",
				"Enchanted Seed Pack",
			},
			Upgrade = {
				Mode = "Order", -- Order (mean will up on order), Chepest, Highest
				Order = { -- top upgrade first, not put mean not upgrade
					"Fairy Spawn Amount",
					"Loose Fairy Spawn Amount",
					"Glimmer Multiplier",
					"Fairy Event Duration",
				},
				Limit = {
					["Glimmer Multiplier"] = 10, -- max 10
					["Loose Fairy Spawn Amount"] = 4, -- max 4
					["Fairy Event Duration"] = 10, -- max 10
					["Fairy Spawn Amount"] = 9, -- max 9
				}
			}
		},
		MaxMoney_Restocks = 8_000_000_000,
		Shop = { -- delete -- to buy
			"Skyroot Chest",
			"Sprout Egg",
			"Sprout Seed Pack",
			-- "Mandrake",
			--"Silver Fertilizer",
			-- "Canary Melon",
			-- "Amberheart",
			--["Spriggan"] = 8,
			-- Friend Shop
			--"Pet Shard GiantBean",
		},
		["Traveling Shop"] = {
            "Bee Egg",
			"Bald Eagle",
            "Cauliflower",
            "Rafflesia",
            "Green Apple",
            "Avocado",
            "Banana",
            "Pineapple",
            "Kiwi",
            "Bell Pepper",
            "Prickly Pear",
            "Loquat",
            "Feijoa",
            "Pitcher Plant",
            "Flower Seed Pack",
			"Common Summer Egg",
			"Rare Summer Egg",
			"Paradise Egg"

		},
		Craft = {
			"Sprout Egg",
			"Anti Bee Egg",
			"Primal Egg",
			"Ancient Seed Pack",
			--"Honeysuckle",
			--"Lightning Rod",
		},
		Start_Do_Honey = 100_000
	},
	
	Gear = {
		Buy = { 
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Medium Toy",
			"Medium Treat",
			"Level Up Lollipop",
			"LevelUp Lollipop",
			"Tanning Mirror",
			"Grandmaster Sprinkler",
		},
		Lock = {

		},
	},

	Eggs = {
		Place = {
			"Enchanted Egg",
			"Bug Egg",
			"Paradise Egg",
			"Sprout Egg",
			--"Gourmet Egg",
			--"Zen Egg",
			"Anti Bee Egg",
			--"Primal Egg",
			--"Night Egg",
			--"Dinosaur Egg",
			--"Oasis Egg",
			"Mythical Egg",
			"Legendary Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg",
			"Uncommon Egg",
		},
		Buy = {
			"Enchanted Egg",
			"Sprout Egg",
			--"Gourmet Egg",
			--"Zen Egg",
			--"Primal Egg",
			--"Night Egg",
			"Bug Egg",
			"Anti Bee Egg",
			--"Dinosaur Egg",
			--"Oasis Egg",
			"Paradise Egg",
			"Mythical Egg",
			"Legendary Egg",
			"Bee Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg",
			"Uncommon Egg",
			"Common Egg",
		}
	},
	
	Pets = {
		["Auto Feed"] = true,

		["Start Delete Pet At"] = 40,
		["Upgrade Slot"] = {
			["Pet"] = {
				--["Bacon Pig"] = { 8, 75, 1 },
				["Glimmering Sprite"] = { 8, 101, 1 },
				["Starfish"] = { 8, 75, 2 },
				["Chicken"] = { 8 , 75, 3 },
				["Rooster"] = { 8, 75, 3 },
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				["Glimmering Sprite"] = { 8, 101, 1 },
				["Tarantula Hawk"] = { 2, 101, 2 },
				--["Gorilla Chef"] = { 8, 101, 1 },
				--["Bacon Pig"] = { 8, 101, 2 },
				--["Tanchozuru"] = { 8, 101, 3 },
				--["Kappa"] = { 8, 101, 4 },
				--["Spaghetti Sloth"] = { 8, 101, 5 },
				--["Corrupted Kodama"] = { 8, 101, 6 },
				--["Kodama"] = { 8, 101, 7 },
				["Blood Kiwi"] = { 8, 101, 3 },
				["Rooster"] = { 8, 101, 4 },
				["Sunny-Side Chicken"] = { 1, 101, 5 },
				["Chicken"] = { 8 , 101, 6 },
				["Starfish"] = { 8, 75, 7 },
			},
		},
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		Locked = {
			"Disco Bee",
			"Butterfly",
			"Mimic Octopus",
			"Queen Bee",
			"Dragonfly",
			"Raccoon",
			"Red Fox",
			"Fennec Fox",
			"Bald Eagle",
			"T-Rex",
			"Brontosaurus",
			"Spinosaurus",
			"Kitsune",
			"Dilophosaurus",
			"Corrupted Kitsune",
			"Raiju",
			"French Fry Ferret",
			"Lobster Thermidor",
			"Golden Goose",
			"Griffin",
			"Cockatrice",
			["Glimmering Sprite"] = 8,
			["Sunny-Side Chicken"] = 1,
			["Tarantula Hawk"] = 2,
			["Bald Eagle"] = 5,
			["Moon Cat"] = 10,
			["Chicken"] = 8,
			["Rooster"] = 2,
			["Blood Kiwi"] = 5,
			["Starfish"] = 8,
		},
		LockPet_Weight = 5, -- if Weight >= 7 they will locked,
		Instant_Sell = {
			"Grey Mouse",
			"Squirrel",
			"Snail",
			"Orangutan",
			"Brown Mouse",
			"Bunny",
			"Crab",
			"Caterpillar",
			"Shiba Inu",
			"Tanuki",
			"Manaki-Neko",
			"Seagull",
			"Bagel Bunny",
			"Bacon Pig",
			"Dairy Cow",
			"Pancake Mole",
			"Hotdog Daschund",
			"Gorilla Chef",
			"Seedling",
			"Sushi Bear",
			"Jackalope",
			"Black Bunny",
			"Deer",
			"Spotted Deer",
			"Pig",
			"Elk",
			"Monkey",
			"Mandrake",
		}
	},

	Webhook = {
		UrlPet = "https://discord.com/api/webhooks/1399732832762331177/PVr6gW2RG2Gokz2CQEtZuJ_BplaBiIZmd8hzTj1Q8FkdoBdCjGo62NuKW0_6puoYpZLS",
		UrlSeed = "",
		PcName = "Remialoveneko",
		
		Noti = {
			Seeds = {
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Honeysuckle",
				"Bone Blossom",
				"Fossilight",
				"Maple Apple",
				"Grand Tomato",
				"Cyclamen",
				"Wispwing",
			},
			SeedPack = {
				"Idk"
			},
			Pets = {
				"Disco Bee",
				"Butterfly",
				"Mimic Octopus",
				"Queen Bee",
				"Dragonfly",
				"Raccoon",
				"Red Fox",
				"Fennec Fox",
				"Bald Eagle",
				"T-Rex",
				"Brontosaurus",
				"Spinosaurus",
				"Dilophosaurus",
				"Ankylosaurus",
				"Kitsune",
				"Corrupted Kitsune",
				"Raiju",
				"French Fry Ferret",
				"Lobster Thermidor",
				"Golden Goose",
				"Griffin",
				"Cockatrice",
			},
			Pet_Weight_Noti = true,
		}
	},
}
License = "O0ckL79tK6KwnmX2uanEfo7bosg2uYQt"
loadstring(game:HttpGet('https://raw.githubusercontent.com/Real-Aya/Loader/main/Init.lua'))()
--https://discord.com/api/webhooks/1399732832762331177/PVr6gW2RG2Gokz2CQEtZuJ_BplaBiIZmd8hzTj1Q8FkdoBdCjGo62NuKW0_6puoYpZLS
