task.wait()
getgenv().ConfigsKaitun = {
	Beta_Fix_Data_Sync = true,

	NoDeletePlayer = false,

	["Block Pet Gift"] = true,

	Collect_Cooldown = 150,

	["Low Cpu"] = true,
	["Auto Rejoin"] = true,

	["Rejoin When Update"] = true,

	["Auto Trade Pet"] = { -- not done yet bro dont use
		["Enabled"] = false,
		["Target"] = {  -- multi users
			"",
		},
		["Pet To Send"] = {
		}
	},

	["Limit Tree"] = {
		["Limit"] = 250,
		["Destroy Untill"] = 250,

		["Safe Tree"] = {
			"Moon Blossom",
			"Bone Blossom",
			"Moon Melon",
			"Maple Apple",
			"Moon Mango",
			"Dragon Pepper",
			"Elephant Ears",
			"Fossilight",
			"Princess Thorn",
			-- for the event
			Bamboo = 4,
			Coconut = 4,
			Mushroom = 4,
			Glowthorn = 4,
			Tomato = 4,
			Pumpkin = 4,
			Pepper = 4,
			Cacao = 4,
			Apple = 4,
			Romanesco = 4,
			["Elder Strawberry"] = 4,
			["Burning Bud"] = 4,
			["Giant Pinecone"] = 4,
			Corn = 4,
			["Sugar Apple"] = 4,
			["Ember Lily"] = 4,
			["Dragon Fruit"] = 4,
			Sunbulb = 8,
			["Orange Tulip"] = 4,
			Blueberry = 4,
			Watermelon = 4,
			Mango = 4,
			Cactus = 4,
			Strawberry = 4,
			Beanstalk = 4,
			Lightshoot = 4,
			Grape = 4,
			Daffodil = 4,
		}
	},

	Seed = {
		Buy = {
			Mode = "Custom", -- Custom , Auto
			Custom = {
				"Carrot",
                "Blueberry",
                "Grape",
                "Strawberry",
                "Elder Strawberry",
                "Wild Carrot",
                "Taro Flower",
                "Mandrake",
                "Rhubarb",
                "Onion",
                "Tall Asparagus",
                "Candy Sunflowers",
                "Red Lollipop",
                "Sugarglaze",
                "Cherry Blossom",
                "Crocus",
                "Daffodil",
                "Orange Tulip",
                "Nightshade",
                "Moonflower",
                "Moon Blossom",
                "Rose",
                "Foxglove",
                "Lilac",
                "Pink Lily",
                "Purple Dagila",
                "Sunflower",
                "Lavender",
                "Honeysuckle",
                "Manuka Flower",
                "Ember Lily",
                "Parasol Flower",
                "Rosy Delight",
                "Lily Of The Valley",
                "Burning Bud",
                "Rafflesia",
                "Stonebite",
                "Liberty Lily",
                "Firework Flower",
                "Serenity",
                "Moboblooma",
                "Soft Sunshine",
                "Hinomai",
                "Zenflare",
                "Dezen",
                "Artichoke",
                "Veinpetal",
                "Flare Daisy",
                "Tranquil Bloom",
                "Apple",
                "Avocado",
                "Banana",
                "Coconut",
                "Dragon Fruit",
                "Durian",
                "Mango",
                "Pear",
                "Pineapple",
                "Watermelon",
                "Starfruit",
                "Blood Banana",
                "Moon Melon",
                "Moon Mango",
                "Nectarine",
                "Hive Fruit",
                "Green Apple",
                "Sugar Apple",
                "Traveler's Fruit",
                "Loquat",
                "Kiwi",
                "Maple Apple",
                "Spiked Mango",
                "Crown Melon",
                "Grand Tomato",
                "Pricklefruit",
                "Mangosteen",
                "Canary Melon",
                "Pumpkin",
                "Tomato",
                "Cantaloupe",
                "Cacao",
                "Beanstalk",
                "Mint",
                "Moonglow",
                "Elephant Ears",
                "Cauliflower",
                "Pitcher Plant",
                "Firefly Fern",
                "Giant Pinecone",
                "Soft Sunshine",
                "Dragon Sapling",
                "Sakura Bush",
                "Princess Thorn",
                "Romanesco",
                "Nectar Thorn",
                "Papaya",
                "Cocovine",
                "Pepper",
                "Dragon Pepper",
                "Bell Pepper",
                "Jalapeno",
                "Badlands Pepper",
                "Feijoa",
                "Duskpuff",
                "Gleamroot",
                "Amberheart",
                "Cactus",
                "Horned Dinoshroom",
                "Twisted Tangle",
                "Sinisterdrip",
                "Amber Spine",
                "Mushroom",
                "Grand Volcania",
                "Bamboo",
                "Bendboo",
                "Lotus",
                "Lucky Bamboo",
                "Spring Onion",
                "Poseidon Plant",
                "Delphinium",
                "Guanabanana",
                "Butternut Squash",
                "Paradise Petal",
                "Boneboo",
                "Fossilight",
                "Bone Blossom",
                "Gorsetail",
                "Lingonberry",
                "Zen Rocks",
                "Enkaku",
                "Corn",
				"Crown of Thorns",
				"Calla Lily",
				"Cyclamen",
				"Sunbulb",
				"Glowthorn",
				"Lightshoot",
				"Briar Rose",
				"Spirit Flower",
				"Wispwing",
			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot"
			},
			Lock = {
				"Maple Apple",
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Moon Melon",
				"Easter Egg",
				"Moon Mango",
				"Bone Blossom",
				"Fossilight",
			}
		}
	},

	["Seed Pack"] = {
		Locked = {

		}
	},


	Events = {
		["Fairy Event"] = {
			Minimum_Money = 100000, -- minimum money to start play this event
			Rewards_Item = { -- top mean select first
				"Pet Shard Glimmering",
				"Enchanted Egg",
				"Mutation Spray Glimmering",
				"FairyPoints",
				"Fairy Targeter",
				"Enchanted Seed Pack",
			},
			Upgrade = {
				Mode = "Order", -- Order (mean will up on order), Chepest, Highest
				Order = { -- top upgrade first, not put mean not upgrade
					"Fairy Spawn Amount",
					"Loose Fairy Spawn Amount",
					"Glimmer Multiplier",
					"Fairy Event Duration",
				},
		Limit = {
					["Glimmer Multiplier"] = 10, -- max 10
					["Loose Fairy Spawn Amount"] = 10, -- max 10
					["Fairy Event Duration"] = 10, -- max 10
					["Fairy Spawn Amount"] = 9, -- max 9
				}
			}
		},
		MaxMoney_Restocks = 10_000_000_000,
		Shop = { -- un comment to buy
			"Enchanted Chest",
			"Pet Shard Glimmering",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			-- "Drake",

			"Sprout Seed Pack",
			"Sprout Egg",
			-- "Mandrake",
			"Silver Fertilizer",
			-- "Canary Melon",
			-- "Amberheart",
			["Spriggan"] = 8,
			-- Friend Shop
			"Skyroot Chest",
			"Pet Shard GiantBean",
		},
		["Traveling Shop"] = {
			"Bee Egg",
			"Paradise Egg", 
			"Rare Summer Egg", 
			"Common Summer Egg"
		},
		Craft = {
			"Enchanted Chest",
			"Fairy Net",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			"Anti Bee Egg",
			"Pet Shard GiantBean",
			"Sprout Egg",
		},
		Start_Do_Honey = 100_000
	},

	Gear = {
		Buy = { 
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Medium Treat",
			"Medium Toy",
			"Harvest Tool",
		},
		Lock = {
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
		},
	},

	Eggs = {
		Place = {
			"Enchanted Egg",
			"Sprout Egg",
			--"Gourmet Egg",
			--"Zen Egg",
			"Anti Bee Egg",
			--"Primal Egg",
			"Bug Egg",
			"Paradise Egg",
			--"Night Egg",
			--"Dinosaur Egg",
			--"Oasis Egg",
			--"Mythical Egg",
			--"Legendary Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg",
			--"Uncommon Egg",
		},
		Buy = {
			"Sprout Egg",
			--"Gourmet Egg",
			--"Zen Egg",
			--"Primal Egg",
			--"Night Egg",
			"Bug Egg",
			"Anti Bee Egg",
			--"Dinosaur Egg",
			--"Oasis Egg",
			"Paradise Egg",
			--"Mythical Egg",
			--"Legendary Egg",
			"Bee Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg",
			"Uncommon Egg",
			"Common Egg",
		}
	},

	Pets = {
		["Auto Feed"] = true,
		MutationPet = {
			["PET NAME"] = {}
		},

	Pets = {
		["Auto Feed"] = true,

		MutationPet = {
			["PET NAME"] = { "Glimmering","... any other" }
		},

		["Start Delete Pet At"] = 40,
		["Upgrade Slot"] = {
			["Little Auto Equip"] = true, -- when it no target pet in list it will equip random/smart before real list have pet
			["Pet"] = {
				["Starfish"] = { 5, 100, 1, true }, -- the "true" on the last is auto equip (use for like only need to use for upgrade pet)
			},
			["Limit Upgrade"] = 2, -- max is 5 (more than or lower than 1 will do nothing)
			["Equip When Done"] = {
				["Glimmering Sprite"] = {8, 100, 1},
				["Tanchozuru"] = { 5, 100, 2 }, -- 5 on the first mean equip only 5 | pet , 100 mean equip only level pet lower than 100 | the one on the last is priority it will ues first if possible 
				["Ostrich"] = { 3, 100, 2 },
				["Blood Kiwi"] = { 8, 100 },
				["Seal"] = { 8, 100 },
				["Rooster"] = { 8, 100 },
				["Starfish"] = { 5, 75 },
			},
		},
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		Locked = {
			"Disco Bee",
			"Butterfly",
			"Mimic Octopus",
			"Queen Bee",
			"Dragonfly",
			"Raccoon",
			"Red Fox",
			"Fennec Fox",
			"Bald Eagle",
			"T-Rex",
			"Brontosaurus",
			"Spinosaurus",
			"Kitsune",
			"Dilophosaurus",
			"Corrupted Kitsune",
			"Raiju",
			"French Fry Ferret",
			"Lobster Thermidor",
			"Golden Goose",
			"Griffin",
			"Cockatrice",
			["Glimmering Sprite"] = 8,
			["Sunny-Side Chicken"] = 1,
			["Tarantula Hawk"] = 2,
			["Bald Eagle"] = 5,
			["Moon Cat"] = 10,
			["Chicken"] = 8,
			["Rooster"] = 2,
			["Blood Kiwi"] = 5,
			["Starfish"] = 8,
		},
		LockPet_Weight = 5, -- if Weight >= 7 they will locked,
		Instant_Sell = {
			"Grey Mouse",
			"Squirrel",
			"Snail",
			"Orangutan",
			"Brown Mouse",
			"Bunny",
			"Crab",
			"Caterpillar",
			"Shiba Inu",
			"Tanuki",
			"Manaki-Neko",
			"Seagull",
			"Bagel Bunny",
			"Bacon Pig",
			"Dairy Cow",
			"Pancake Mole",
			"Hotdog Daschund",
			"Gorilla Chef",
			"Seedling",
			"Sushi Bear",
			"Jackalope",
			"Black Bunny",
			"Deer",
			"Spotted Deer",
			"Pig",
			"Elk",
			"Monkey",
			"Mandrake",
		}
	},

	Webhook = {
		UrlPet = "https://discord.com/api/webhooks/1399732832762331177/PVr6gW2RG2Gokz2CQEtZuJ_BplaBiIZmd8hzTj1Q8FkdoBdCjGo62NuKW0_6puoYpZLS",
		UrlSeed = "",
		PcName = "RemiaGenPhoenix",
		
		Noti = {
			Seeds = {
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Honeysuckle",
				"Bone Blossom",
				"Fossilight",
				"Maple Apple",
				"Grand Tomato",
				"Cyclamen",
				"Wispwing",
			},
			SeedPack = {
				"Idk"
			},
			Pets = {
				"Disco Bee",
				"Butterfly",
				"Mimic Octopus",
				"Queen Bee",
				"Dragonfly",
				"Raccoon",
				"Red Fox",
				"Fennec Fox",
				"Bald Eagle",
				"T-Rex",
				"Brontosaurus",
				"Spinosaurus",
				"Dilophosaurus",
				"Ankylosaurus",
				"Kitsune",
				"Corrupted Kitsune",
				"Raiju",
				"French Fry Ferret",
				"Lobster Thermidor",
				"Golden Goose",
				"Griffin",
				"Cockatrice",
			},
			Pet_Weight_Noti = true,
		}
	},
}
License = "O0ckL79tK6KwnmX2uanEfo7bosg2uYQt"
loadstring(game:HttpGet('https://raw.githubusercontent.com/Real-Aya/Loader/main/Init.lua'))()
--https://discord.com/api/webhooks/1399732832762331177/PVr6gW2RG2Gokz2CQEtZuJ_BplaBiIZmd8hzTj1Q8FkdoBdCjGo62NuKW0_6puoYpZLS
